language: go
go:
    - 1.12.x
before_install:
    - nvm install 10.15.3
    - npm config set spin false
    - npm install -g yarn
before_script:
    - yarn install
services:
    - redis-server
env:
    global:
        - GO111MODULE=on
        - REDIS_URL=redis://localhost:6379
