language: go
go:
    - 1.12.x
before_install:
    - nvm install 10.15.3
    - npm config set spin false
    - npm install -g yarn
before_script:
    - yarn install
    - psql -c 'create database test;' -U postgres
    - bin/go-post-compile
    - goose -dir=database/migrations -v postgres $DATABASE_URL up
services:
    - redis-server
    - postgresql
env:
    global:
        - GO111MODULE=on
        - REDIS_URL=redis://localhost:6379
        - DATABASE_URL=postgres://postgres:@localhost:5432/test?sslmode=disable
