version: '3'
services:
  app:
    build: .
    volumes:
      - ./:/go/src/github.com/ppworks/go-playground
    ports:
      - 3000:3000
    environment:
      - REDIS_URL=redis://redis:6379
  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
