version: '3'
services:
  app:
    build: ./docker/app
    volumes:
      - ./:/go/src/github.com/ppworks/go-playground
    ports:
      - 3000:3000
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://postgres:@db:5432/postgres?sslmode=disable
  webpack:
    image: node:latest
    command: bash -c "npm install --ignore-optional && npm start"
    working_dir: /usr/src/app/frontend
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/frontend/node_modules # コンテナ内のnode_modulesをvolumesに登録
    ports:
      - 8080:8080
  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  db:
    image: postgres:11.2-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - LANG=ja_JP.utf8
volumes:
  redis:
    driver: local
  postgres:
    driver: local
